"""Add user_id to workshops for user ownership

Revision ID: 1434fda8849a
Revises: cac93f7dcb32
Create Date: 2025-12-09 11:55:06.608086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1434fda8849a'
down_revision = 'cac93f7dcb32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workshops', schema=None) as batch_op:
        # Add column as nullable first to handle existing data
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_workshops_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_workshops_user_id', 'users', ['user_id'], ['id'])
    
    # Set user_id to admin user (id=1) for existing workshops
    op.execute('UPDATE workshops SET user_id = 1 WHERE user_id IS NULL')
    
    # Now make it non-nullable
    with op.batch_alter_table('workshops', schema=None) as batch_op:
        batch_op.alter_column('user_id', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workshops', schema=None) as batch_op:
        batch_op.drop_constraint('fk_workshops_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_workshops_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
